"""Make vendor_id nullable, add vendor_name_raw, add VENDOR_UNRESOLVED exception

Revision ID: 3b0b755b7ab5
Revises: 7ffbb0f64dc0
Create Date: 2026-10-03 22:28:55.528971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0b755b7ab5'
down_revision: Union[str, Sequence[str], None] = '7ffbb0f64dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('vendor_name_raw', sa.String(length=255), nullable=True))
    op.alter_column('invoices', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # Add new enum value
    op.execute("ALTER TYPE exceptiontype ADD VALUE 'VENDOR_UNRESOLVED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete any exceptions that use VENDOR_UNRESOLVED before removing the column
    # PostgreSQL does not support dropping enum values (e.g. ALTER TYPE ... DROP VALUE) natively.
    # To fully remove it, we would need to rename the type, recreate it without the value, and cast columns.
    # For safety in this downgrade, we will delete the exceptions using this type, but leave the type in the enum.
    op.execute("DELETE FROM invoice_exceptions WHERE exception_type = 'VENDOR_UNRESOLVED'")

    # Delete invoices that have no vendor_id before setting it to NOT NULL
    # This cascades to verifications and invoice_items
    op.execute("DELETE FROM invoices WHERE vendor_id IS NULL")

    op.alter_column('invoices', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoices', 'vendor_name_raw')
    # ### end Alembic commands ###
