"""add_po_item_id_to_invoice_items

Revision ID: 43d01a680b7c
Revises: 66c7633fe3c5
Create Date: 2026-10-06 08:41:05.064238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d01a680b7c'
down_revision: Union[str, Sequence[str], None] = '3b0b755b7ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('po_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoice_items_po_item_id'), 'invoice_items', ['po_item_id'], unique=False)
    op.create_foreign_key(None, 'invoice_items', 'purchase_order_items', ['po_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_items_po_item_id'), table_name='invoice_items')
    op.drop_column('invoice_items', 'po_item_id')
    # ### end Alembic commands ###
