"""Add line_item_id to InvoiceException

Revision ID: 7ffbb0f64dc0
Revises: 23f20707c74c
Create Date: 2026-10-03 20:58:25.738464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffbb0f64dc0'
down_revision: Union[str, Sequence[str], None] = '23f20707c74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_exceptions', sa.Column('line_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoice_exceptions_line_item_id'), 'invoice_exceptions', ['line_item_id'], unique=False)
    op.create_foreign_key('fk_invoice_exceptions_line_item_id', 'invoice_exceptions', 'invoice_items', ['line_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoice_exceptions_line_item_id', 'invoice_exceptions', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_exceptions_line_item_id'), table_name='invoice_exceptions')
    op.drop_column('invoice_exceptions', 'line_item_id')
    # ### end Alembic commands ###
